install.packages('pacman', repos='http://cran.us.r-project.org')
install.packages('BiocManager', repos='http://cran.us.r-project.org')
install.packages('usethis')
install.packages('devtools')
devtools::install_version("RcppAnnoy", version = "0.0.16", repos="http://cran.us.r-project.org")
BiocManager::install("BiocNeighbors")
devtools::install_version("RcppAnnoy", version = "0.0.18", repos="http://cran.us.r-project.org")
BiocManager::install("SingleR")
BiocManager::install("limma")
BiocManager::install("SingleCellExperiment")
devtools::install_version(package = 'rsvd', version = package_version('1.0.2'), repos = 'http://cran.us.r-project.org')
devtools::install_version(package = 'Seurat', version = package_version('3.2.3'), repos = 'http://cran.us.r-project.org')
install.packages('https://cran.r-project.org/src/contrib/Archive/spatstat/spatstat_1.64-1.tar.gz', repos=NULL,type='source', INSTALL_opts = '--no-lock')
devtools::install_version(package = 'Seurat', version = package_version('3.2.3'), repos = 'http://cran.us.r-project.org',dependencies = F)
list.p=c("dplyr","Matrix","future","pheatmap","ggplot2","optparse","hdf5r");pacman::p_load(list.p, character.only = TRUE)
